# pylint: disable=duplicate-code
from .conventions import Brain, Convention
from .installer import (
    BLOCK_PATTERN,
    END_MARKER,
    HOOK_COMMAND,
    HOOK_ENTRY,
    HOOK_EVENT,
    SNIPPET,
    START_MARKER,
    Client,
    InvalidConfigError,
    McpConfigFormat,
    Scope,
    SnippetBlock,
    clients,
    detect_installed_clients,
    detect_snippet_blocks,
    install,
    install_hook,
    install_mcp_config,
    uninstall,
    uninstall_hook,
    uninstall_mcp_config,
)
from .settings import Settings
from .updater import update, update_command

__all__ = [
    "BLOCK_PATTERN",
    "END_MARKER",
    "HOOK_COMMAND",
    "HOOK_ENTRY",
    "HOOK_EVENT",
    "SNIPPET",
    "START_MARKER",
    "Brain",
    "Client",
    "Convention",
    "InvalidConfigError",
    "McpConfigFormat",
    "Scope",
    "Settings",
    "SnippetBlock",
    "clients",
    "detect_installed_clients",
    "detect_snippet_blocks",
    "install",
    "install_hook",
    "install_mcp_config",
    "uninstall",
    "uninstall_hook",
    "uninstall_mcp_config",
    "update",
    "update_command",
]
