name: Snyk Security with uv

on:
  push:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 00:00 every Sunday

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: '3.13'

      - name: Export dependencies
        run: uv export --format requirements-txt --output-file requirements.txt

      - name: Run Snyk Open Source
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
